insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (1, '14 Goodland Alley', 4752, 'CABA', 3, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (2, '296 Mandrake Drive', 2371, 'CABA', 4, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (3, '98462 Butterfield Court', 3202, 'CABA', 4, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (4, '569 Stuart Alley', 3245, 'CABA', 1, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (5, '50 Columbus Street', 1454, 'CABA', 3, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (6, '07 Jenna Way', 2218, 'CABA', 4, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (7, '3 Mockingbird Alley', 1761, 'CABA', 2, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (8, '987 Village Plaza', 3040, 'Norrbotten', 1, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (9, '46 Myrtle Terrace', 4104, 'Dalarna', 2, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (10, '4 Village Green Drive', 7702, 'CABA', 2, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (11, '2592 Anthes Drive', 7492, 'CABA', 3, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (12, '2 Laurel Way', 5473, 'CABA', 4, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (13, '4 Sauthoff Court', 3800, 'CABA', 4, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (14, '5 Hansons Parkway', 1012, 'CABA', 3, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (15, '1983 Chinook Circle', 5227, 'CABA', 3, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (16, '0995 Roth Center', 6101, 'CABA', 2, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (17, '28 Commercial Pass', 1405, 'CABA', 2, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (18, '16943 Boyd Center', 6666, 'Kalmar', 1, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (19, '60 Kedzie Pass', 5802, 'CABA', 4, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (20, '102 Hermina Hill', 5379, 'CABA', 3, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (21, '72 Hudson Center', 6739, 'CABA', 4, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (22, '70398 Susan Drive', 3111, 'CABA', 3, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (23, '43963 Ridgeview Crossing', 1283, 'CABA', 3, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (24, '155 Harper Place', 1284, 'CABA', 3, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (25, '1653 Chinook Parkway', 1301, 'CABA', 4, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (26, '1 Fuller Hill', 7714, 'CABA', 3, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (27, '9495 Westport Way', 7547, 'CABA', 1, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (28, '71 Ridge Oak Pass', 4085, 'Lisboa', 2, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (29, '1 Welch Plaza', 3710, 'CABA', 4, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (30, '291 Fremont Hill', 3005, 'CABA', 1, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (31, '97 Helena Point', 5658, 'Florida', 4, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (32, '1 Manufacturers Court', 4772, 'Tennessee', 2, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (33, '7851 Melody Way', 1083, 'CABA', 4, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (34, '550 Prairie Rose Lane', 3003, 'CABA', 2, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (35, '25 Dakota Center', 6098, 'Västra Götaland', 4, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (36, '039 Walton Alley', 7047, 'CABA', 4, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (37, '969 Glacier Hill Crossing', 2297, 'Stockholm', 1, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (38, '91 Prentice Plaza', 2603, 'New Jersey', 3, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (39, '6650 Express Trail', 4654, 'CABA', 2, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (40, '93 Portage Drive', 1405, 'CABA', 3, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (41, '401 Fair Oaks Trail', 1175, 'CABA', 4, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (42, '04155 Declaration Alley', 1690, 'CABA', 2, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (43, '452 Caliangt Trail', 1755, 'CABA', 2, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (44, '52180 Dottie Plaza', 6160, 'CABA', 2, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (45, '804 Mariners Cove Circle', 4380, 'CABA', 1, 1, true);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (46, '8 Westerfield Road', 2036, 'CABA', 4, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (47, '7 Mendota Parkway', 7426, 'CABA', 2, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (48, '1358 Stang Park', 1586, 'CABA', 3, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (49, '2311 Eggendart Street', 7984, 'CABA', 1, 1, false);
insert into domicilios (user_id, calle, cp, localidad, provincia_id, pais_id, envio) values (50, '75699 Lawn Park', 5138, 'Ontario', 4, 1, true);
